services:
  - type: web
    name: metube-zh
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: TZ
        value: Asia/Shanghai
      - key: DEFAULT_THEME
        value: dark
      - key: DOWNLOAD_DIR
        value: /tmp/downloads
      - key: STATE_DIR
        value: /tmp/downloads/.metube
      - key: TEMP_DIR
        value: /tmp/downloads
      - key: AUDIO_DOWNLOAD_DIR
        value: /tmp/downloads
